---
title: "Supplementary materials"
format: html
---

# Appendix {.appendix .unnumbered}

## Statistcal model for addition rate {.appendix .unnumbered}

$$
\begin{aligned}
&\text{[Likelihood]} \\
\text{Addition Rate}_i &\sim \operatorname{Beta}(\mu_i \phi_i, (1 - \mu_i) \phi_i) \\
\ \\
&\text{[} \mu \text{ part of beta distribution]} \\
\mu_i &= \operatorname{logit}^{-1}(\eta_i) = \frac{1}{1 + e^{-\eta_i}} \\
\eta_i &=  \alpha_{\text{translator}[i]} + \gamma_{\text{poem}[i]} + \beta_{\text{translation focus}[i]} \\
\ \\
&\text{[} \phi \text{ part of beta distribution]} \\
\log(\phi_i) &= \gamma^{\phi}_{\text{poem}[i]} \\
\ \\
& \text{[Group-specific intercepts]} \\
\alpha_{j} &\sim \mathcal{N}(\mu_{\alpha_j}, \sigma_{\text{translator}}), \text{ for } j \text{ in translator} 1, 2, \dots, 10 \\
\gamma_{j} &\sim \mathcal{N}(0, \sigma_{\text{poem}}), \text{ for } j \text{ in poem} 1, 2, \dots, 1000 \\
\gamma^{\phi}_{j} &\sim \mathcal{N}(\mu_{\gamma^{\phi}_{j}}, \sigma^{\phi}_{\text{poem}}), \text{ for } j \text{ in poem} 1, 2, \dots, 1000 \\
\ \\
& \text{[Prior for fixed coefficients]} \\
\beta_{j} &\sim \text{Student-t}(3, 0, 2.5), \text{ for } j \text{ in translation focus} 1, 2, 3, 4\\
\ \\
& \text{[Prior for population-level intercepts]} \\
\mu_{\alpha_{j}}, \mu_{\gamma^{\phi}_{j}} &\sim \text{Student-t}(3, 0, 2.5) \\
\ \\
& \text{[Prior for hyperparameter]} \\
\sigma_{\text{translator}}, \sigma_{\text{poem}}, \sigma^{\phi}_{\text{poem}} &\sim \text{Student-t}(3, 0, 2.5)
\end{aligned}
$$



Here^[Note that while the model is written in Centered Parameterization, its implementation in `brms` uses Non-Centered Parameterization.]:

- $\text{Addition Rate}_i$ refers to the addition rate and is assumed to follow a beta distribution.
- $\mu_i \phi_i$ and $(1 - \mu_i) \phi_i$ correspond to the shape parameters of the beta distribution.
- $\mu_i$ is the mean parameter of the beta distribution, obtained by applying a logistic transformation to the linear predictor $\eta_i$.
- $\beta_{\text{translation focus}[i]}$, where $\text{translation focus} = 1, 2, 3, 4$, represents the fixed effect for the four translation approaches, modeling a distinct effect for each translation approach.
- $\alpha_{\text{translator}[i]}$, where $\text{translator} = 1, 2, \dots, 10$, represents the random effect term (random intercept) for the translators.
- $\gamma_{\text{poem}[i]}$, where $\text{poem} = 1, 2, \dots, 1000$, represents the random effect term (random intercept) for the poems (PoemID).
- $\phi_i$ is the precision parameter of the beta distribution and is modeled by the random effect term $\gamma^{\phi}_{\text{poem}[i]}$ for the poems (PoemID).
- $\mu_{\alpha_j}$ and $\mu_{\gamma^{\phi}_{j}}$ are the population-level intercepts for the $\mu$ part and the $\phi$ part, respectively.

Regarding the prior distributions, we generally follow the default settings in `brms`:
- The intercepts $\mu_{\alpha_j}$, $\mu_{\gamma^{\phi}_{j}}$, and the fixed effects $\beta_{\text{translation focus}}$ for each translation approach are assumed to follow Student-t prior distributions (the default prior distribution in `brms`).
- $\sigma_{\text{translator}}$, $\sigma_{\text{poem}}$, and $\sigma^{\phi}_{\text{poem}}$ represent the standard deviations of the random effect terms for the translators, poems, and precision parameters, respectively, and are assumed to follow Student-t distributions (the default prior distribution in `brms`).

Refer to the following table for the default priors:

```{R}
#| label: tbl-model-configs
#| tbl-scap: Default proirs
#| tbl-cap: Default proirs
#| warining: false

formula |> get_prior(
  formula, data=data, family = Beta(),
  prior= prior
  ) |> 
  kable()
```

```{R}
#| label: model-info
#| tbl-cap: Model details

model |> summary()
```

<!-- $$ -->
<!-- \begin{aligned} -->
<!-- &\text{[Likelihood]} \\ -->
<!-- \text{Addition Rate}_i &\sim \operatorname{Beta}(\mu_i \phi_i, (1 - \mu_i) \phi_i) \\ -->
<!-- \ \\ -->
<!-- &\text{[} \mu \text{ part of beta distribution]} \\ -->
<!-- \mu_i &= \operatorname{logit}^{-1}(\eta_i) = \frac{1}{1 + e^{-\eta_i}} \\ -->
<!-- \eta_i &= + u_{\text{translator}_i} + u_{\text{poem}_i} + \text{\textbf{Translation focus}}_i \boldsymbol{\beta} \\ -->
<!-- \text{\textbf{Translation focus}} &= (\text{Text-focused}\; \text{Translator-focused}\; \text{Reader-focused}\; \text{Others}) \\ -->
<!-- \boldsymbol{\beta} &= (\beta_{0}\; \beta_{1}\; \beta_{2}\; \beta_{3})^{\intercal} \\ -->
<!-- \ \\ -->
<!-- &\text{[} \phi \text{ part of beta distribution]} \\ -->
<!-- \log(\phi_i) &= u_{\phi_{\text{poem}_i}} \\ -->
<!-- \ \\ -->
<!-- & \text{[Translator- and Poem-specific random intercepts]} \\ -->
<!-- u_{\text{translator}_i} &\sim \mathcal{N}(\mu_{\text{translator}}, \sigma_{\text{translator}}^2) \\ -->
<!-- u_{\text{poem}_i} &\sim \mathcal{N}(\mu_{\text{poem}}, \sigma_{\text{poem}}^2) \\ -->
<!-- u_{\phi_{\text{poem}_i}} &\sim \mathcal{N}(\mu_{\phi_{\text{poem}}}, \sigma_{\phi_{\text{poem}}}^2) \\ -->
<!-- \ \\ -->
<!-- &\text{[Priors]} \\ -->
<!-- \beta_{0} &\sim \text{Student-t}(3, 0, 2.5) \\ -->
<!-- \beta_{1}, \beta_{2},\beta_{3} &\sim \operatorname{Uniform}(0, 1) \\ -->
<!-- \sigma_{\text{translator}}, \sigma_{\text{poem}}, \sigma_{\phi_{\text{poem}}} &\sim \text{Student-t}(3, 0, 2.5) -->
<!-- \end{aligned} -->
<!-- $$ -->

<!-- - $\text{Addition Rate}_i$ は追加率であり、ベータ分布に従うと仮定する。 -->
<!-- - $\mu_i \phi_i, (1 - \mu_i) \phi_i$ はそれぞれベータ分布の形状パラメータに相当する。 -->
<!-- - $\mu_i$ はベータ分布の平均値パラメータであり、線形予測子 $\eta_i$ をロジスティック変換することで得られる。線形予測子 $\eta_i$ において、 -->
<!--   - $\boldsymbol{\beta}$ は翻訳観の固定効果項である。 $\beta_{1},\beta_{2},\beta_{3},\beta_{4}$ で構成される。 -->
<!--   - $u_{\text{translator}_i}$ は訳者のランダム効果項（ランダム切片）であり、 $u_{\text{poem}_i}$ はランダム効果項（ランダム切片）である。 -->
<!-- - $\phi_i$ はベータ分布の精度パラメータであり、詩 (PoemID) のランダム効果項 $u_{\phi_{\text{poem}_i}}$ で予測される。 -->
<!-- - 固定効果項 $\boldsymbol{\beta}$ の各要素は Student-t 分布の事前分布を用いる（`brms`のデフォルト事前分布）。 -->
<!-- - $\sigma_{\text{translator}}$, $\sigma_{\text{poem}}$, $\sigma_{\phi_{\text{poem}}}$ はそれぞれ、訳者および詩歌、精度パラメータに対するランダム効果項の標準偏差であり、Student-t 分布に従うと仮定される（`brms`のデフォルト事前分布）。 -->


<!-- $$\text{AdditionRate}_i \sim \text{Beta}(\mu_i \cdot \phi_i, (1 - \mu_i) \cdot \phi_i)$$ -->
<!-- $$\mu_i = \text{logit}^{-1}(\eta_i) = \frac{1}{1 + e^{-\eta_i}}$$ -->
<!-- $$\eta_i = \beta_0 + \beta_{\text{focus}} \cdot \text{focus}_i + u_{\text{translator}_i} + u_{\text{poem}_i}$$ -->
<!-- $$\phi_i = \phi_0 + u_{\phi_{\text{poem}_i}}$$ -->
<!-- $$\beta_0, \beta_{\text{focus}}, \phi_0 \sim \text{Student-t}(3, 0, 2.5)$$ -->
<!-- $$u_{\text{translator}_i} \sim \mathcal{N}(0, \sigma_{\text{translator}}^2)$$ -->
<!-- $$u_{\text{poem}_i} \sim \mathcal{N}(0, \sigma_{\text{poem}}^2)$$ -->
<!-- $$u_{\phi_{\text{poem}_i}} \sim \mathcal{N}(0, \sigma_{\phi_{\text{poem}}}^2)$$ -->
<!-- $$\sigma_{\text{translator}}, \sigma_{\text{poem}}, \sigma_{\phi_{\text{poem}}} \sim \text{Student-t}(3, 0, 2.5)$$ -->

<!-- ここで: -->

<!-- - $\text{Addition Rate}_i$ は追加率であり、ベータ分布に従う。 -->
<!-- - $\mu_i$ はベータ分布の平均値であり、線形予測子 $\eta_i$ をロジスティック変換することで得られる。 -->
<!-- - $\phi_i$ はベータ分布の精度パラメータであり、詩歌 ($\text{PoemID}$) ごとに異なるランダム効果 $u_{\phi_{\text{poem}_i}}$ を持つと仮定される。 -->
<!-- - $\mu_i \cdot \phi_i, (1 - \mu_i) \cdot \phi_i$ はそれぞれベータ分布の形状パラメータに相当する。 -->
<!-- - $\eta_i$ は線形予測子であり、翻訳観の固定効果 ($\beta_{\text{focus}}$)、訳者のランダム効果 ($u_{\text{translator}_i}$)、および詩歌のランダム効果 ($u_{\text{poem}_i}$) を含む。 -->
<!-- - $\phi_i$ は詩歌レベルでのランダム効果を持つ精度パラメータであり，$\phi_0$ という切片と詩歌のランダム効果の和として表現される。 -->
<!-- - $\beta_0$ は切片であり、追加率の平均を示す。 -->
<!-- - $\beta_{\text{focus}}$ は翻訳観の回帰係数であり、翻訳観が追加率に与える固定効果を評価する。 -->
<!-- - $\phi_0$ は精度パラメータ $\phi_i$ の切片であり、Student-t 分布に従うと仮定される。 -->
<!-- - $u_{\text{translator}_i}$ は訳者のランダム効果であり、訳者間の変動を制御する。これは正規分布に従うと仮定される。 -->
<!-- - $u_{\text{poem}_i}$ は詩歌のランダム効果であり、詩歌間の変動を制御する。これは正規分布に従うと仮定される。 -->
<!-- - $u_{\phi_{\text{poem}_i}}$ は精度パラメータ $\phi_i$ の詩歌ごとのランダム効果であり、正規分布に従うと仮定される。 -->
<!-- - $\sigma_{\text{translator}}$, $\sigma_{\text{poem}}$, $\sigma_{\phi_{\text{poem}}}$ はそれぞれ、訳者および詩歌、精度パラメータに対するランダム効果の標準偏差であり、Student-t 分布に従うと仮定される。 -->

## "Tatsuta" poem #698 {#sec-app-tatsuta .appendix .unnumbered}

```{bash}
#| label: tatsuta
#| include: false

tatsuta=$(sh ./scripts/query_poem.sh たつた)
echo "$tatsuta" > ./cache/tatsuta.txt
tatsuta_hachidai=$(echo "$tatsuta" | grep -E "^0.:000... \| ")
echo "Document frequency = "$(echo "$tatsuta_hachidai" | wc -l)
echo "$tatsuta_hachidai"
```

```{bash}
#| label: tatsuta-kokinshu

tatsuta_kokin=$(cat ./cache/tatsuta.txt | grep -E "^01:000... \| ") 
echo "Document frequency = "$(echo "$tatsuta_kokin" | wc -l)
echo "$tatsuta_kokin"
```

```{bash}
#| label: content-word-count

echo "High frequency content collocates of tatsuta:"
cat ./cache/tatsuta.txt | grep -vE "\|" | grep -vE "たつた" | awk '$4 <= 60' | awk '{ 
      suffix = ""
      if ($2 ~ /^[CE]/) { suffix = suffix "+" }
      if ($2 !~ ".0.") { suffix = suffix "*" }
      print $0 suffix
  }' | awk '{print $3 "|" $6 $10}' | sort | uniq -c | sort -nr | awk '$1 >= 5'|\
  awk '{printf "%4d. %s\n", NR, $0}'
```

```{bash}
#| label: function-word-count

echo "High frequency function collocates of tatsuta:"
cat ./cache/tatsuta.txt | grep -vE "\|" | grep -vE "たつた" | awk '$4 > 60' | awk '{ 
      suffix = ""
      if ($2 ~ /^[CE]/) { suffix = suffix "+" }
      if ($2 !~ ".0.") { suffix = suffix "*" }
      print $0 suffix
  }' | awk '{print $3 "|" $6 $10}' | sort | uniq -c | sort -nr | awk '$1 >= 5'|\
  awk '{printf "%4d. %s\n", NR, $0}'
```

```{bash}
#| label: alignment-results

sh ./scripts/pipe_examples.sh
```